baseURL = "http://blog.gethin.online/reveal"
languageCode = "en-us"
title = "GETHIN'S HUGO REVEAL"

theme = "reveal-hugo"

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[params.reveal_hugo]
theme = "blood"


